-- No-op: replaced by domain migration approach in middleware
-- Custom domains are handled at the platform level, not per-tenant
-- giro-kids.com is the new APP_DOMAIN; dadosinteligentes.app.br becomes legacy with 301 redirects
